name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: node -v

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start server
        run: nohup node src/index.js > server.log 2>&1 &
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/checkout@v3
      - name: Wait for server to start
        run: sleep 10
      - run: curl http://localhost:3000/test

