name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: node -v

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start server
        run: |
          nohup node src/index.js --host=localhost --port=3000 > server.log 2>&1 &
          sleep 5  # Wait for the server to start
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/checkout@v3
      - name: Wait for server to start
        run: sleep 10  # Adjust this wait time as needed
      - name: Check server status
        run: cat server.log  # Print server logs to see if there are any errors
      - run: curl http://localhost:3000/test
