name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: node -v
  
  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v3
      - name: Start server
        run: node src/index.js
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/checkout@v3
      - name: Wait for server to start
        run: |
          for i in {1..10}; do
            if curl -sSf http://localhost:3000/test &> /dev/null; then
              echo "Server is ready"
              break
            else
              echo "Retrying... Attempt $i"
              sleep 5
            fi
          done
      - run: curl http://localhost:3000/test
