name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Check node version
        run: node -v

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v3
      - name: Test NodeJS
        run: node src/test.js
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Server
        run: node src/server.js &
