name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    workflow_dispatch:

  jobs:
    build-job:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - run: node -v
    
    test-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: node src/index.js
    
    deploy-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - run: firefox http://localhost:3000/test