name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: node -v
  
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: node src/index.js
        background: true
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - uses: actions/checkout@v3
      - name: Esperando o server iniciar
        run: sleep 10
      - run: firefox http://localhost:3000/test